services:
  api:
    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
