services:
  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  app-network:
    driver: bridge
